#!/bin/sh

#
# To run the deform demo selenium tests:
#
# check out deform:
#
#   svn co $REPOZE_SVN/deform/trunk deform
#
# create a virtualenv in the top level of the deform checkout within an
# "env" subdir:
#
#   virtualenv --no-site-packages env
#
# run setup.py develop using the new virtualenv python in the deform checkout:
#
#   env/bin/python setup.py develop
#
# install the demo extra:
#
#   bin/easy_install deform[demo]
#
# start the deform demo app in one console:
#
#   bin/paster serve deformdemo/demo.ini
#
# start the selenium server on another console:
#
#   java -jar selenium-server.jar
#
# run this shell script "seleniumtests":
#
#  ./seleniumtests
#

env/bin/python deformdemo/tests/test_demo.py
